BINARY_NAME=hodlbook
COMMIT=$(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
LDFLAGS=-ldflags "-s -w -X main.version=$(VERSION) -X main.commit=$(COMMIT) -X main.date=$(DATE)"


bump-version:
	@if [ -z "$(TYPE)" ]; then \
		echo "Error: TYPE argument (major, feat, fix) is required."; \
		echo "Usage: make bump-version TYPE=fix"; \
		exit 1; \
	fi
	@echo "Running tests..."
	@if ! $(MAKE) test; then \
		echo "Tests failed. Aborting version bump."; \
		exit 1; \
	fi
	@CURRENT_VERSION=$$(grep -oP 'const Version = "\K[^"]+' version/version.go); \
	if [ -z "$$CURRENT_VERSION" ]; then \
		echo "Error: Could not read current version from version/version.go."; \
		exit 1; \
	fi; \
	echo "Current version: $$CURRENT_VERSION"; \
	MAJOR=$$(echo $$CURRENT_VERSION | cut -d. -f1 | tr -d 'v'); \
	MINOR=$$(echo $$CURRENT_VERSION | cut -d. -f2); \
	PATCH=$$(echo $$CURRENT_VERSION | cut -d. -f3); \
	if [ -z "$$MAJOR" ]; then MAJOR=0; fi; \
	if [ -z "$$MINOR" ]; then MINOR=0; fi; \
	if [ -z "$$PATCH" ]; then PATCH=0; fi; \
	case "$(TYPE)" in \
		major) MAJOR=$$((MAJOR + 1)); MINOR=0; PATCH=0 ;; \
		feat) MINOR=$$((MINOR + 1)); PATCH=0 ;; \
		fix) PATCH=$$((PATCH + 1)) ;; \
		*) echo "Invalid TYPE: $(TYPE). Use 'major', 'feat', or 'fix'."; exit 1 ;; \
	esac; \
	NEW_VERSION="v$$MAJOR.$$MINOR.$$PATCH"; \
	VERSION_NUM="$$MAJOR.$$MINOR.$$PATCH"; \
	echo "New version: $$NEW_VERSION"; \
	echo ""; \
	echo "Updating version/version.go..."; \
	mkdir -p version; \
	echo "// Code generated by Makefile. DO NOT EDIT." > version/version.go; \
	echo "package version" >> version/version.go; \
	echo "" >> version/version.go; \
	echo "const Version = \"$$NEW_VERSION\"" >> version/version.go; \
	echo "const Date = \"$(DATE)\"" >> version/version.go; \
	echo "Updating umbrel/umbrel-app.yml..."; \
	sed -i "s/^version: .*/version: \"$$VERSION_NUM\"/" umbrel/umbrel-app.yml; \
	echo "Updating umbrel/docker-compose.yml image tag..."; \
	sed -i "s|image: ghcr.io/hodlbook/hodlbook:.*|image: ghcr.io/hodlbook/hodlbook:$$NEW_VERSION|" umbrel/docker-compose.yml; \
	echo ""; \
	echo "Creating release branch..."; \
	BRANCH_NAME="release/$$NEW_VERSION"; \
	git checkout -b $$BRANCH_NAME; \
	git add version/version.go umbrel/umbrel-app.yml umbrel/docker-compose.yml; \
	git commit -m "Bump version to $$NEW_VERSION"; \
	git push origin $$BRANCH_NAME; \
	echo ""; \
	echo "Release branch $$BRANCH_NAME pushed."; \
	echo "Run: make release"

release:
	@VERSION=$$(grep -oP 'const Version = "\K[^"]+' version/version.go); \
	if [ -z "$$VERSION" ]; then \
		echo "Error: Could not read version from version/version.go."; \
		exit 1; \
	fi; \
	BRANCH_NAME="release/$$VERSION"; \
	echo "Creating release for $$VERSION from $$BRANCH_NAME..."; \
	git fetch origin $$BRANCH_NAME; \
	git checkout $$BRANCH_NAME; \
	git pull origin $$BRANCH_NAME; \
	echo "Creating tag $$VERSION..."; \
	git tag $$VERSION; \
	echo "Pushing tag to trigger GitHub Actions..."; \
	git push origin $$VERSION

test:
	@echo "Running tests..."
	@go test ./...
